name: Build and Upload Artifact

on:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - run: pipx run build

      - uses: actions/upload-artifact@v4
        with:
          name: distfiles
          path: dist/
          if-no-files-found: error
